version: '3.1'

services:
  database:
    image: "postgres:13.4"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: user
      POSTGRES_DB: bank_database