export const CUSTOMER_REGISTER_REQUEST = "CUSTOMER_REGISTER_REQUEST";
export const CUSTOMER_REGISTER_SUCCESS = "CUSTOMER_REGISTER_SUCCESS";
export const CUSTOMER_REGISTER_FAIL = "CUSTOMER_REGISTER_FAIL";
export const CUSTOMER_REGISTER_RESET = "CUSTOMER_REGISTER_RESET";

export const CUSTOMER_REMOVE_FROM_STORAGE = "CUSTOMER_REMOVE_FROM_STORAGE";

export const CUSTOMER_SEARCH_BY_IDENTITY_REQUEST =
  "CUSTOMER_SEARCH_BY_IDENTITY_REQUEST";
export const CUSTOMER_SEARCH_BY_IDENTITY_SUCCESS =
  "CUSTOMER_SEARCH_BY_IDENTITY_SUCCESS";
export const CUSTOMER_SEARCH_BY_IDENTITY_FAIL =
  "CUSTOMER_SEARCH_BY_IDENTITY_FAIL";
export const CUSTOMER_SEARCH_BY_IDENTITY_RESET =
  "CUSTOMER_SEARCH_BY_IDENTITY_RESET";

export const CUSTOMER_SEARCH_BY_ID_REQUEST = "CUSTOMER_SEARCH_BY_ID_REQUEST";
export const CUSTOMER_SEARCH_BY_ID_SUCCESS = "CUSTOMER_SEARCH_BY_ID_SUCCESS";
export const CUSTOMER_SEARCH_BY_ID_FAIL = "CUSTOMER_SEARCH_BY_ID_FAIL";
export const CUSTOMER_SEARCH_BY_ID_RESET = "CUSTOMER_SEARCH_BY_ID_RESET";

export const CUSTOMER_UPDATE_SALARY_REQUEST = "CUSTOMER_UPDATE_SALARY_REQUEST";
export const CUSTOMER_UPDATE_SALARY_SUCCESS = "CUSTOMER_UPDATE_SALARY_SUCCESS";
export const CUSTOMER_UPDATE_SALARY_FAIL = "CUSTOMER_UPDATE_SALARY_FAIL";
export const CUSTOMER_UPDATE_SALARY_RESET = "CUSTOMER_UPDATE_SALARY_RESET";

export const CUSTOMER_UPDATE_STATUS_REQUEST = "CUSTOMER_UPDATE_STATUS_REQUEST";
export const CUSTOMER_UPDATE_STATUS_SUCCESS = "CUSTOMER_UPDATE_STATUS_SUCCESS";
export const CUSTOMER_UPDATE_STATUS_FAIL = "CUSTOMER_UPDATE_STATUS_FAIL";
export const CUSTOMER_UPDATE_STATUS_RESET = "CUSTOMER_UPDATE_STATUS_RESET";
