export const CREDIT_INFORMATION_INQUIRY_REQUEST =
  "CREDIT_INFORMATION_INQUIRY_REQUEST";
export const CREDIT_INFORMATION_INQUIRY_SUCCESS =
  "CREDIT_INFORMATION_INQUIRY_SUCCESS";
export const CREDIT_INFORMATION_INQUIRY_FAIL =
  "CREDIT_INFORMATION_INQUIRY_FAIL";
export const CREDIT_INFORMATION_INQUIRY_RESET =
  "CREDIT_INFORMATION_INQUIRY_RESET";

export const CREDIT_APPLICATION_REQUEST = "CREDIT_APPLICATION_REQUEST";
export const CREDIT_APPLICATION_SUCCESS = "CREDIT_APPLICATION_SUCCESS";
export const CREDIT_APPLICATION_FAIL = "CREDIT_APPLICATION_FAIL";
export const CREDIT_APPLICATION_RESET = "CREDIT_APPLICATION_RESET";
