export const CREDIT_INFORMATION_INQUIRY_REQUEST =
  "CREDIT_INFORMATION_INQUIRY_REQUEST";
export const CREDIT_INFORMATION_INQUIRY_SUCCESS =
  "CREDIT_INFORMATION_INQUIRY_SUCCESS";
export const CREDIT_INFORMATION_INQUIRY_FAIL =
  "CREDIT_INFORMATION_INQUIRY_FAIL";
export const CREDIT_INFORMATION_INQUIRY_RESET =
  "CREDIT_INFORMATION_INQUIRY_RESET";
