export const CUSTOMER_REGISTER_REQUEST = "CUSTOEMR_REGISTER_REQUEST";
export const CUSTOMER_REGISTER_SUCCESS = "CUSTOEMR_REGISTER_SUCCESS";
export const CUSTOMER_REGISTER_FAIL = "CUSTOEMR_REGISTER_FAIL";
export const CUSTOMER_REGISTERY_RESET = "CUSTOMER_REGISTERY_RESET";

export const CUSTOMER_REMOVE_FROM_STORAGE = "CUSTOMER_REMOVE_FROM_STORAGE";
