export const CUSTOMER_REGISTER_REQUEST = "CUSTOMER_REGISTER_REQUEST";
export const CUSTOMER_REGISTER_SUCCESS = "CUSTOMER_REGISTER_SUCCESS";
export const CUSTOMER_REGISTER_FAIL = "CUSTOMER_REGISTER_FAIL";
export const CUSTOMER_REGISTERY_RESET = "CUSTOMER_REGISTERY_RESET";

export const CUSTOMER_REMOVE_FROM_STORAGE = "CUSTOMER_REMOVE_FROM_STORAGE";

export const CUSTOMER_SEARCH_BY_IDENTITY_REQUEST =
  "CUSTOMER_SEARCH_BY_IDENTITY_REQUEST";
export const CUSTOMER_SEARCH_BY_IDENTITY_SUCCESS =
  "CUSTOMER_SEARCH_BY_IDENTITY_SUCCESS";
export const CUSTOMER_SEARCH_BY_IDENTITY_FAIL =
  "CUSTOMER_SEARCH_BY_IDENTITY_FAIL";
export const CUSTOMER_SEARCH_BY_IDENTITY_RESET =
  "CUSTOMER_SEARCH_BY_IDENTITY_RESET";

export const CUSTOMER_SEARCH_BY_ID_REQUEST = "CUSTOMER_SEARCH_BY_ID_REQUEST";
export const CUSTOMER_SEARCH_BY_ID_SUCCESS = "CUSTOMER_SEARCH_BY_ID_SUCCESS";
export const CUSTOMER_SEARCH_BY_ID_FAIL = "CUSTOMER_SEARCH_BY_ID_FAIL";
export const CUSTOMER_SEARCH_BY_ID_RESET = "CUSTOMER_SEARCH_BY_ID_RESET";
